(define (make-frame variables values)
  (map cons variables values))
(define (frame-variables frame)
  (map car frame))
(define (frame-values frame)
  (map cdr frame))
(define (add-binding-to-frame! var val frame)
  (let ((first-pair (car frame)))
    (set-car! frame (cons var val))
    (set-cdr! frame (list first-pair (cdr frame)))))
